import Link from "next/link";
import { openSubmissionAction, restoreAction, softDeleteAction } from "@/app/actions";
import { categoryLabels, contentStatusLabel } from "@/lib/config";
import { formatDate } from "@/lib/view";

type Item = Awaited<ReturnType<typeof import("@/lib/data").getHostSubmissions>>[number];
export function HostCard({ item, returnTo }: { item: Item; returnTo: string }) {
  return <article className={`panel host-card ${item.deletedAt?"deleted":""}`}><div className="card-top"><span className={`category category-${item.category}`}>{categoryLabels[item.category]}</span><span className="status">{contentStatusLabel(item.category,item.contentStatus)}</span>{item.hostReadAt?<span className="read-state">投稿已查看</span>:<span className="unread-pill">新投稿</span>}{item.pinnedAt?<span className="pin">📌 已置顶</span>:null}</div><h2>{item.title}</h2><p className="description">{item.description||"没有填写推荐介绍"}</p><div className="record-meta"><span>投稿者：{item.username}{item.anonymousPublic?"（公开匿名）":""}</span><span>投稿于 {formatDate(item.createdAt)}</span>{item.publishedAt?<span>首次公开于 {formatDate(item.publishedAt)}</span>:null}</div>{item.deletedAt?<NoticeRestore item={item} returnTo={returnTo}/>:<div className="record-actions">{item.hostReadAt?<Link className="button small primary" href={`/host/submission/${item.id}`}>打开详情</Link>:<form action={openSubmissionAction}><input type="hidden" name="submissionId" value={item.id}/><button className="button small primary" type="submit">打开并公开</button></form>}<form action={softDeleteAction}><input type="hidden" name="submissionId" value={item.id}/><input type="hidden" name="returnTo" value={returnTo}/><button className="button small danger" type="submit">删除</button></form></div>}</article>;
}
function NoticeRestore({item,returnTo}:{item:Item;returnTo:string}){return <div className="undo-box"><span>这条投稿已软删除，公开页面已隐藏。</span><form action={restoreAction}><input type="hidden" name="submissionId" value={item.id}/><input type="hidden" name="returnTo" value={returnTo}/><button className="button small ghost" type="submit">恢复投稿</button></form></div>}
