"use client";
import { useState } from "react";
import { themeAction } from "@/app/actions";
import { StyledSelect } from "@/components/styled-select";
import type { SiteSetting } from "@/db/schema";
export function ThemeEditor({settings}:{settings:SiteSetting}){
  const [colors,setColors]=useState({primary:settings.primaryColor,secondary:settings.secondaryColor,accent:settings.accentColor,background:settings.backgroundColor,opacity:Number(settings.cardOpacity),overlay:Number(settings.backgroundOverlay)});
  const [background,setBackground]=useState(settings.backgroundType==="custom"&&settings.backgroundImageUrl?settings.backgroundImageUrl:settings.backgroundImageUrl?.startsWith("builtin:")?settings.backgroundImageUrl:"builtin:warm");
  const set=(key:keyof typeof colors,value:string|number)=>setColors(old=>({...old,[key]:value}));
  return <form className="theme-layout" action={themeAction}><section className="panel stack theme-controls"><h2>品牌文字</h2><label>网站名称<input name="siteName" defaultValue={settings.siteName} maxLength={50} required/></label><label>网站副标题<textarea name="siteTagline" defaultValue={settings.siteTagline} maxLength={120}/></label><h2>背景</h2><StyledSelect label="背景样式" value={background} onValueChange={setBackground} options={[{value:"builtin:warm",label:"暖阳圆点"},{value:"builtin:stars",label:"轻快星星"},{value:"builtin:bubbles",label:"柔软气泡"},...(settings.backgroundType==="custom"&&settings.backgroundImageUrl?[{value:settings.backgroundImageUrl,label:"自定义背景"}]:[])]}/><input type="hidden" name="backgroundType" value={background.startsWith("builtin:")?"built_in":"custom"}/><input type="hidden" name="backgroundImageUrl" value={background}/><h2>配色</h2><div className="color-grid"><Color name="primaryColor" label="主色" value={colors.primary} onChange={v=>set("primary",v)}/><Color name="secondaryColor" label="辅助色" value={colors.secondary} onChange={v=>set("secondary",v)}/><Color name="accentColor" label="强调色" value={colors.accent} onChange={v=>set("accent",v)}/><Color name="backgroundColor" label="页面背景" value={colors.background} onChange={v=>set("background",v)}/></div><label>卡片透明度 <b>{colors.opacity.toFixed(2)}</b><input name="cardOpacity" type="range" min="0.7" max="1" step="0.01" value={colors.opacity} onChange={e=>set("opacity",Number(e.target.value))}/></label><label>背景遮罩 <b>{colors.overlay.toFixed(2)}</b><input name="backgroundOverlay" type="range" min="0" max="0.85" step="0.01" value={colors.overlay} onChange={e=>set("overlay",Number(e.target.value))}/></label><button className="button primary" type="submit">保存主题</button></section><section className="theme-preview-wrap"><span className="eyebrow">实时预览</span><div className="theme-preview" style={{backgroundColor:colors.background,"--preview-primary":colors.primary,"--preview-secondary":colors.secondary,"--preview-accent":colors.accent,"--preview-opacity":colors.opacity} as React.CSSProperties}><div className="preview-cloud">☁︎</div><article><span>番剧</span><h3>一部让人想聊很久的作品</h3><p>卡片与背景预览。</p><button type="button">神绮爱感想</button></article></div></section></form>
}
function Color({name,label,value,onChange}:{name:string;label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<span className="color-input"><input name={name} type="color" value={value} onChange={e=>onChange(e.target.value)}/><code>{value}</code></span></label>}
