import type { Metadata } from "next";
import { createHostRecommendationAction } from "@/app/actions";
import { Notice } from "@/components/notice";
import { StyledSelect } from "@/components/styled-select";
import { categories, categoryLabels, submissionKinds, type SubmissionKind } from "@/lib/config";
export const metadata: Metadata = { title: "撰写原创推荐" };
export default async function HostRecommendPage({ searchParams }: { searchParams: Promise<{ error?: string; kind?: string }> }) {
  const { error, kind: rawKind } = await searchParams;
  const kind: SubmissionKind = submissionKinds.includes(rawKind as SubmissionKind) ? rawKind as SubmissionKind : "work";
  const workCategories = categories.filter((item) => item !== "food" && item !== "wish");
  const fixedCategory = kind === "food" ? "food" : kind === "wish" ? "wish" : "";
  return <><header className="host-heading"><div><span className="eyebrow">Host original</span><h1>{kind === "food" ? "写美食推荐" : kind === "wish" ? "发布直播预告" : "写原创推荐"}</h1><p>{kind === "wish" ? "发布后作为未完成的直播计划展示。" : "发布后自动归类为已完成。"}</p></div></header><nav className="submission-kind-switch host-kind-switch" aria-label="选择原创栏目"><a className={kind === "work" ? "is-active" : ""} href="/host/recommend">推荐单</a><a className={kind === "wish" ? "is-active" : ""} href="/host/recommend?kind=wish">许愿箱</a><a className={kind === "food" ? "is-active" : ""} href="/host/recommend?kind=food">美食家</a></nav><Notice>{error}</Notice><form className="panel stack host-recommend-form" action={createHostRecommendationAction}>{kind === "work" ? <StyledSelect name="category" label="作品分类" required defaultValue="" options={[{value:"",label:"选择分类",disabled:true},...workCategories.map((category)=>({value:category,label:categoryLabels[category]}))]}/> : <input name="category" type="hidden" value={fixedCategory}/>}<label>{kind === "food" ? "店铺 / 菜品名称" : kind === "wish" ? "预告 / 计划标题" : "作品名称"}<input name="title" required maxLength={100} placeholder={kind === "food" ? "店铺 · 菜品" : kind === "wish" ? "下一次想做什么？" : "作品名称"}/></label><label>{kind === "wish" ? "计划说明" : "推荐理由"}<textarea name="description" maxLength={1000} placeholder={kind === "wish" ? "简单介绍这次直播计划。" : "为什么值得推荐？"}/></label><label>{kind === "wish" ? "补充内容" : "体验感想"}<textarea name="experience" maxLength={4000} placeholder={kind === "wish" ? "可留空，之后再补充" : "你的真实感想"}/></label><div className="split">{kind !== "wish" ? <StyledSelect name="score" label="评分（10 分制）" defaultValue="" helper="可稍后修改。" options={[{value:"",label:"暂不评分"},...[10,9,8,7,6,5,4,3,2,1].map((score)=>({value:String(score),label:`${score} / 10`}))]}/> : <input name="score" type="hidden" value=""/>}<label>相关链接（选填）<input name="externalUrl" type="url" placeholder="https://…"/></label></div><label className="checkbox"><input name="pin" type="checkbox"/><span>直接置顶<span className="helper">所有排序均优先。</span></span></label><label>{kind === "wish" ? "预定说明（选填）" : "置顶推荐语（选填）"}<textarea name="pinNote" maxLength={300}/></label><button className="button primary" type="submit">{kind === "wish" ? "发布到许愿箱" : "发布推荐"}</button></form></>;
}
