import type { Metadata } from "next";
import { createHostRecommendationAction } from "@/app/actions";
import { Notice } from "@/components/notice";
import { categories, categoryLabels, contentStatusLabel, contentStatuses } from "@/lib/config";
export const metadata: Metadata = { title: "撰写原创推荐" };
export default async function HostRecommendPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return <><header className="host-heading"><div><span className="eyebrow">Host original</span><h1>撰写神绮爱原创推荐</h1><p>发布后直接进入公开推荐库，不经过投稿收件箱。之后仍可修改状态、评分、感想和置顶。</p></div></header><Notice>{error}</Notice><form className="panel stack host-recommend-form" action={createHostRecommendationAction}><div className="split"><label>分类<select name="category" required defaultValue=""><option value="" disabled>选择分类</option>{categories.map((category) => <option value={category} key={category}>{categoryLabels[category]}</option>)}</select></label><label>当前状态<select name="contentStatus" defaultValue="completed">{contentStatuses.map((status) => <option value={status} key={status}>{contentStatusLabel("game", status)}</option>)}</select></label></div><label>作品名称<input name="title" required maxLength={100} placeholder="想推荐给粉丝的作品" /></label><label>推荐理由<textarea name="description" maxLength={1000} placeholder="为什么值得推荐？可以直接写 BV 号，发布后会自动变成蓝色链接。" /></label><label>游玩 / 阅读 / 观看感想<textarea name="experience" maxLength={4000} placeholder="记录完成后的真实感想，也可以稍后在详情页补写。" /></label><div className="split"><label>评分（10 分制）<select name="score" defaultValue=""><option value="">暂不评分</option>{[10,9,8,7,6,5,4,3,2,1].map((score) => <option value={score} key={score}>{score} / 10</option>)}</select><span className="helper">只有状态为“已玩 / 已完成”时可以评分。</span></label><label>相关链接（选填）<input name="externalUrl" type="url" placeholder="https://…" /></label></div><label className="checkbox"><input name="pin" type="checkbox" /><span>发布时直接置顶<span className="helper">置顶内容在时间和评分排序中都会排在最前。</span></span></label><label>置顶推荐语（选填）<textarea name="pinNote" maxLength={300} /></label><button className="button primary" type="submit">直接公开这条神绮爱推荐</button></form></>;
}
